name:  Custom Nginx Docker Image Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Print environment info
        run: |
          whoami
          id
          ls -l /var/run/docker.sock || echo "No docker socket"
          docker info || echo "Docker not available"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Custom Nginx Docker Image
        run: 
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/github-actions-nginx:latest-${{ github.sha }} -f ./task-1/Dockerfile .

      - name: Push Custom Nginx Docker Image to Docker Hub
        run: 
          docker push ${{ vars.DOCKERHUB_USERNAME }}/github-actions-nginx:latest-${{ github.sha }}